opendata_stack_platform_dbt:
  target: "{{ env_var('DBT_TARGET', 'personal') }}"
  outputs:
    local:
      type: duckdb
      path: ../data/nyc_database.duckdb
    personal:
      type: duckdb
      path: ../data/nyc_database.duckdb