opendata_stack_platform_dbt:
  target: "{{ env_var('DBT_TARGET', 'personal') }}"
  outputs:
    prod:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE', '../data/nyc_database.duckdb') }}"
      threads: 4
    dev:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE', '../data/nyc_database.duckdb') }}"
      threads: 4
    personal:
      type: duckdb
      path: "{{ env_var('DUCKDB_DATABASE', '../data/nyc_database.duckdb') }}"
      threads: 4
