directory_type = "workspace"

[workspace]

[[workspace.projects]]
path = "projects/physical_risk_impact"

[[workspace.projects]]
path = "projects/data_platform"

[[workspace.projects]]
path = "projects/ml_regression_model"

[[workspace.projects]]
path = "projects/streamify"
