# --- Gateway Connection ---
gateways:
  duckdb:
    connection:
      type: duckdb
      extensions:
        - httpfs
        - aws
        - ducklake
        - spatial
      catalogs:
        duckdb: "{{ env_var('DUCKDB_DATABASE', '../data/nyc_database.duckdb') }}"
        ducklake:
          type: ducklake
          path: "ducklake:../data/analytics_metadata.ducklake"
          data_path: s3://warehouse
      secrets:
        - type: s3
          key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
          secret: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
          region: "{{ env_var('AWS_REGION', 'us-east-1') }}"
          endpoint: "127.0.0.1:9000"
          use_ssl: False
          url_style: path

default_gateway: duckdb

# --- Model Defaults ---
# https://sqlmesh.readthedocs.io/en/stable/reference/model_configuration/#model-defaults

model_defaults:
  dialect: duckdb
  start: 2024-01-01 # Start date for backfill history
  cron: '@daily'    # Run models daily at 12am UTC (can override per model)

# --- Linting Rules ---
# Enforce standards for your team
# https://sqlmesh.readthedocs.io/en/stable/guides/linter/

linter:
  enabled: true
  rules:
    - ambiguousorinvalidcolumn
    - invalidselectstarexpansion
