spark.sql.warehouse.dir s3a://warehouse/
spark.sql.catalogImplementation hive
spark.hadoop.javax.jdo.option.ConnectionURL jdbc:derby:;databaseName=metastore_db;create=true
spark.hadoop.javax.jdo.option.ConnectionDriverName org.apache.derby.jdbc.EmbeddedDriver
