version: 2

sources:
  - name: silver_yellow
    description: "Yellow taxi trip data from NYC Open Data portal stored in DuckDB"
    database: "{{ var('database_name', 'nyc_database') }}"
    schema: silver_yellow
    tables:
      - name: taxi_trip
        description: "Yellow taxi trip data at silver layer"
        meta:
          dagster:
            asset_key: ["nyc_database", "silver", "yellow", "taxi_trip"]
        columns:
          - name: vendor_id
            description: "A code indicating the TPEP provider that provided the record"
          - name: tpep_pickup_datetime
            description: "The date and time when the meter was engaged"
          - name: tpep_dropoff_datetime
            description: "The date and time when the meter was disengaged"
          - name: passenger_count
            description: "The number of passengers in the vehicle (driver-entered value)"
          - name: trip_distance
            description: "The elapsed trip distance in miles reported by the taximeter"
          - name: ratecode_id
            description: "The final rate code in effect at the end of the trip"
          - name: store_and_fwd_flag
            description: "Flag indicating whether the trip record was held in vehicle memory before sending to the vendor"
          - name: pu_location_id
            description: "TLC Taxi Zone in which the taximeter was engaged"
          - name: do_location_id
            description: "TLC Taxi Zone in which the taximeter was disengaged"
          - name: payment_type
            description: "A numeric code signifying how the passenger paid for the trip"
          - name: fare_amount
            description: "The time-and-distance fare calculated by the meter"
          - name: extra
            description: "Miscellaneous extras and surcharges"
          - name: mta_tax
            description: "Metropolitan Transportation Authority tax"
          - name: tip_amount
            description: "Tip amount"
          - name: tolls_amount
            description: "Total amount of all tolls paid in the trip"
          - name: improvement_surcharge
            description: "Improvement surcharge assessed on hailed trips"
          - name: total_amount
            description: "The total amount charged to passengers"
          - name: congestion_surcharge
            description: "Total amount collected for NYS congestion surcharge"
          - name: airport_fee
            description: "Fee for trips that start or end at airports"
          - name: row_hash
            description: "Unique hash identifier for the row"
          - name: partition_key
            description: "Partition key for the data, typically in YYYY-MM format"
          - name: _dlt_id
            description: "Unique identifier generated by DLT"
          - name: _dlt_load_id
            description: "Load identifier generated by DLT"

  - name: silver_green
    description: "Green taxi trip data from NYC Open Data portal stored in DuckDB"
    database: "{{ var('database_name', 'nyc_database') }}"
    schema: silver_green
    tables:
      - name: taxi_trip
        description: "Green taxi trip data at silver layer"
        meta:
          dagster:
            asset_key: ["nyc_database", "silver", "green", "taxi_trip"]
        columns:
          - name: vendor_id
            description: "A code indicating the LPEP provider that provided the record"
          - name: lpep_pickup_datetime
            description: "The date and time when the meter was engaged"
          - name: lpep_dropoff_datetime
            description: "The date and time when the meter was disengaged"
          - name: passenger_count
            description: "The number of passengers in the vehicle (driver-entered value)"
          - name: trip_distance
            description: "The elapsed trip distance in miles reported by the taximeter"
          - name: ratecode_id
            description: "The final rate code in effect at the end of the trip"
          - name: store_and_fwd_flag
            description: "Flag indicating whether the trip record was held in vehicle memory before sending to the vendor"
          - name: pu_location_id
            description: "TLC Taxi Zone in which the taximeter was engaged"
          - name: do_location_id
            description: "TLC Taxi Zone in which the taximeter was disengaged"
          - name: payment_type
            description: "A numeric code signifying how the passenger paid for the trip"
          - name: fare_amount
            description: "The time-and-distance fare calculated by the meter"
          - name: extra
            description: "Miscellaneous extras and surcharges"
          - name: mta_tax
            description: "Metropolitan Transportation Authority tax"
          - name: tip_amount
            description: "Tip amount"
          - name: tolls_amount
            description: "Total amount of all tolls paid in the trip"
          - name: improvement_surcharge
            description: "Improvement surcharge assessed on hailed trips"
          - name: total_amount
            description: "The total amount charged to passengers"
          - name: congestion_surcharge
            description: "Total amount collected for NYS congestion surcharge"
          - name: airport_fee
            description: "Fee for trips that start or end at airports"
          - name: trip_type
            description: "A code indicating whether the trip was a street-hail or a dispatch"
          - name: row_hash
            description: "Unique hash identifier for the row"
          - name: partition_key
            description: "Partition key for the data, typically in YYYY-MM format"
          - name: _dlt_id
            description: "Unique identifier generated by DLT"
          - name: _dlt_load_id
            description: "Load identifier generated by DLT"

  - name: silver_fhvhv
    description: "High-Volume For-Hire Vehicle (HVFHV) trip data from NYC Open Data portal stored in DuckDB"
    database: "{{ var('database_name', 'nyc_database') }}"
    schema: silver_fhvhv
    tables:
      - name: taxi_trip
        description: "High-Volume For-Hire Vehicle (HVFHV) trip data at silver layer"
        meta:
          dagster:
            asset_key: ["nyc_database", "silver", "fhvhv", "taxi_trip"]
        columns:
          - name: hvfhs_license_num
            description: "The TLC license number of the HVFHS base or business"
          - name: dispatching_base_num
            description: "The TLC Base License Number of the base that dispatched the trip"
          - name: pickup_datetime
            description: "The date and time of the trip pick-up"
          - name: dropoff_datetime
            description: "The date and time of the trip drop-off"
          - name: originating_base_num
            description: "The base number of the base that received the original trip request"
          - name: request_datetime
            description: "The date and time when the passenger requested to be picked up"
          - name: on_scene_datetime
            description: "The date and time when the driver arrived at the pick-up location"
          - name: trip_miles
            description: "Total miles for the passenger trip"
          - name: trip_time
            description: "Total time in seconds for the passenger trip"
          - name: base_passenger_fare
            description: "Base passenger fare before tolls, tips, taxes, and fees"
          - name: tolls
            description: "Total amount of all tolls paid in the trip"
          - name: bcf
            description: "Total amount collected in the trip for the Black Car Fund"
          - name: sales_tax
            description: "Total amount collected in the trip for NYS sales tax"
          - name: tips
            description: "Total amount of tips received from the passenger"
          - name: driver_pay
            description: "Total driver pay (not including tolls or tips)"
          - name: shared_request_flag
            description: "Indicates if the passenger agreed to a shared/pooled ride"
          - name: shared_match_flag
            description: "Indicates if the passenger shared the vehicle with another passenger"
          - name: access_a_ride_flag
            description: "Indicates if the trip was administered on behalf of the MTA"
          - name: wav_request_flag
            description: "Indicates if the passenger requested a wheelchair-accessible vehicle"
          - name: wav_match_flag
            description: "Indicates if the trip occurred in a wheelchair-accessible vehicle"
          - name: pu_location_id
            description: "TLC Taxi Zone in which the trip began"
          - name: do_location_id
            description: "TLC Taxi Zone in which the trip ended"
          - name: congestion_surcharge
            description: "Total amount collected for NYS congestion surcharge"
          - name: airport_fee
            description: "Fee for trips that start or end at airports"
          - name: row_hash
            description: "Unique hash identifier for the row"
          - name: partition_key
            description: "Partition key for the data, typically in YYYY-MM format"
          - name: _dlt_id
            description: "Unique identifier generated by DLT"
          - name: _dlt_load_id
            description: "Load identifier generated by DLT"

  - name: taxi_zone_lookup
    description: "Lookup table for NYC taxi zones"
    database: "{{ var('database_name', 'nyc_database') }}"
    schema: main
    tables:
      - name: taxi_zone_lookup
        description: "Mapping of location IDs to zone names and boroughs"
        columns:
          - name: zone_id
            description: "Unique identifier for the taxi zone"
          - name: borough_name
            description: "Borough name (Manhattan, Brooklyn, Queens, Bronx, Staten Island)"
            tests:
              - accepted_values:
                  values:
                    - Manhattan
                    - Bronx
                    - Brooklyn
                    - Queens
                    - Staten Island
                    - EWR
          - name: zone_name
            description: "Zone name within the borough"
          - name: geom_data
            description: "Geometry data for the zone"
          - name: area_size
            description: "Area of the zone (in coordinate system units)"
          - name: perimeter_length
            description: "Perimeter of the zone (in coordinate system units)"
